apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: automation
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

